name: "0x00000001"
markdown: redcarpet
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]
baseurl: 'http://nasgoncalves.github.io'

# Information for the Atom feed
gereksiz:
   author: "Nuno Goncalves"
   email: "nuno.alberto.soares.goncalves@gmail.com"
