title: '0x00000001'
email: nasgoncalves@live.com

description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nasgoncalves.github.io"

twitter_username: nasgoncalves
github_username: nasgoncalves

markdown: kramdown
